language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="http://w3c.github.io/gamepad/W3CTRMANIFEST"
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
  - secure: "krgtgnLi0lk0ffVe/HZ3ahsdDxiOvj3coUBj2ps7QsnYWqC3XYdsysusD0hlzlaWGTVqj/91PZFb+WKFhPGhV0t+OlU+/2WP6yYsf/W8LqMJSd/9mQsceeHGbZWQGA8MTRs17Im20e0U6pT7dEFQ0N0k4AaA97ASM1NPEHowwBA="
script:
- echo "ok"
after_success:
- CC="mcaceres@mozilla.com"
- echo "If it fails, check https://lists.w3.org/Archives/Public/public-tr-notifications/"
- curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN" --data "cc=$CC"
